import * as THREE from 'three'
import React, { useMemo, useState, createContext, useContext } from 'react'
import { useGLTF, useCursor, Text, Merged } from '@react-three/drei'
import { useMonitorStore, MonitorData } from '../../store/monitorStore'
import { getHighlightsData } from './highlightsData'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 computers_1-transformed.glb --transform
*/

// Context for instanced meshes
const context = createContext({} as any)

export function Instances({ children, ...props }: any) {
    const { nodes } = useGLTF('/models/computers_1-transformed.glb') as any
    const instances = useMemo(
        () => ({
            Object: nodes.Object_4,
            Object1: nodes.Object_16,
            Object3: nodes.Object_52,
            Object13: nodes.Object_172,
            Object14: nodes.Object_174,
            Object23: nodes.Object_22,
            Object24: nodes.Object_26,
            Object32: nodes.Object_178,
            Object36: nodes.Object_28,
            Object45: nodes.Object_206,
            Object46: nodes.Object_207,
            Object47: nodes.Object_215,
            Object48: nodes.Object_216,
            Sphere: nodes.Sphere,
        }),
        [nodes]
    )
    return (
        <Merged instances={instances} {...props}>
            {(instances: any) => <context.Provider value={instances} children={children} />}
        </Merged>
    )
}

export function Computers(props: any) {
    const instances = useContext(context)

    // Get data for the 9 monitors
    const monitors = useMemo(() => getHighlightsData(), [])

    return (
        <group {...props} dispose={null}>
            {/* Monitor 1: Cognitive Clarity (Top Left ish) */}
            <ScreenInteractive
                frame="Object_206" panel="Object_207"
                position={[-4.76, 2.76, 0.49]} rotation={[0.07, 0.61, -0.04]}
                data={monitors[0]}
            />

            {/* Monitor 2: ConnectDist (Bottom Left) */}
            <ScreenInteractive
                frame="Object_209" panel="Object_210"
                position={[-3.66, 0.44, 0.99]} rotation={[0.08, 0.35, -0.03]}
                data={monitors[1]}
            />

            {/* Monitor 3: AccessTransit (Center Left) */}
            <ScreenInteractive
                frame="Object_212" panel="Object_213"
                position={[-1.76, 3.19, -0.9]} rotation={[0.1, 0.28, -0.03]}
                data={monitors[2]}
            />

            {/* Monitor 4: CICan Navigator (Center Main) */}
            <ScreenInteractive
                frame="Object_215" panel="Object_216"
                position={[0.26, 0.61, -0.03]} rotation={[0.11, 0, -0.03]}
                data={monitors[3]}
            />

            {/* Monitor 5: Sunny's Finance (Center Top) */}
            <ScreenInteractive
                frame="Object_218" panel="Object_219"
                position={[1.54, 3.32, -1.03]} rotation={[0.11, -0.22, -0.04]}
                data={monitors[4]}
            />

            {/* Monitor 6: Portfolio (Right Main) */}
            <ScreenInteractive
                frame="Object_221" panel="Object_222"
                position={[4.05, 0.82, 0.69]} rotation={[0.09, -0.58, -0.04]}
                data={monitors[5]}
            />

            {/* Monitor 7: Hackathon (Right Top) */}
            <ScreenInteractive
                frame="Object_224" panel="Object_225"
                position={[-5.82, 0.81, 2.79]} rotation={[0.05, 0.93, -0.04]}
                data={monitors[6]}
            />

            {/* Monitor 8: CDN Article (Far Top Right) */}
            <ScreenInteractive
                frame="Object_227" panel="Object_228"
                position={[5.25, 3.37, 0.17]} rotation={[0.09, -0.63, -0.04]}
                data={monitors[7]}
            />

            {/* Monitor 9: Design System (Far Right) */}
            <ScreenInteractive
                frame="Object_230" panel="Object_231"
                position={[6.48, 1.34, 3]} rotation={[0.06, -0.96, -0.04]}
                data={monitors[8]}
            />

            {/* Static objects */}
            <instances.Object scale={0.5} position={[-4.76, 2.76, 0.49]} rotation={[0.07, 0.61, -0.04]} />
            <instances.Object1 scale={0.5} position={[1.54, 3.32, -1.03]} rotation={[0.11, -0.22, -0.04]} />
            <instances.Object3 scale={0.5} position={[4.05, 0.82, 0.69]} rotation={[0.09, -0.58, -0.04]} />
            <instances.Object13 scale={0.5} position={[-5.82, 0.81, 2.79]} rotation={[0.05, 0.93, -0.04]} />
            <instances.Object14 scale={0.5} position={[6.48, 1.34, 3]} rotation={[0.06, -0.96, -0.04]} />
            <instances.Object23 scale={0.5} position={[-3.66, 0.44, 0.99]} rotation={[0.08, 0.35, -0.03]} />
            <instances.Object24 scale={0.5} position={[-2.42, -1.03, 1.7]} rotation={[0, 0.53, 0]} />
            <instances.Object32 scale={0.5} position={[-1.76, 3.19, -0.9]} rotation={[0.1, 0.28, -0.03]} />
            <instances.Object36 scale={0.5} position={[0.49, -1.33, 1.83]} rotation={[0, -0.27, 0]} />
            <instances.Object45 scale={0.5} position={[-4.76, 2.76, 0.49]} rotation={[0.07, 0.61, -0.04]} />
            <instances.Object46 scale={0.5} position={[-4.76, 2.76, 0.49]} rotation={[0.07, 0.61, -0.04]} />
            <instances.Object47 scale={0.5} position={[0.26, 0.61, -0.03]} rotation={[0.11, 0, -0.03]} />
            <instances.Object48 scale={0.5} position={[0.26, 0.61, -0.03]} rotation={[0.11, 0, -0.03]} />
            <instances.Sphere scale={0.5} position={[-0.24, -1.36, 1.95]} rotation={[0, 0.2, 0]} />
        </group>
    )
}

function ScreenInteractive({ frame, panel, data, ...props }: any) {
    const { nodes, materials } = useGLTF('/models/computers_1-transformed.glb') as any

    // Store
    const setHovered = useMonitorStore(state => state.setHoveredMonitor)
    const setClicked = useMonitorStore(state => state.setClickedMonitor)

    const [hovered, setHover] = useState(false)

    useCursor(hovered)

    // Handle pointer events
    const onPointerOver = (e: any) => {
        e.stopPropagation()
        setHover(true)
        // Calculate 2D position for tooltip
        // We project the 3D position to 2D screen space
        const vector = new THREE.Vector3().setFromMatrixPosition(e.object.matrixWorld)
        vector.project(e.camera)

        // Normalized device coordinates (-1 to +1) -> Screen coordinates
        const styleX = (vector.x * 0.5 + 0.5) * window.innerWidth
        const styleY = (-(vector.y * 0.5) + 0.5) * window.innerHeight

        setHovered(data, { x: styleX, y: styleY })
    }

    const onPointerOut = () => {
        setHover(false)
        setHovered(null)
    }

    const onClick = (e: any) => {
        e.stopPropagation()
        setClicked(data)
    }

    return (
        <group {...props}>
            <mesh geometry={nodes[frame].geometry} material={materials.Texture} />
            <mesh
                geometry={nodes[panel].geometry}
                material={materials.Texture}
                onPointerOver={onPointerOver}
                onPointerOut={onPointerOut}
                onClick={onClick}
            >
                <meshBasicMaterial color={hovered ? '#ffffff' : '#000000'} />
            </mesh>

            {/* Screen Content - Title */}
            <ScreenText
                position={[0, 0, 0.07]} // Slightly in front of screen
                title={data.title}
                color={data.color}
                hovered={hovered}
            />
        </group>
    )
}

function ScreenText({ title, color, hovered, ...props }: any) {
    return (
        <Text
            fontSize={0.25}
            letterSpacing={-0.05}
            color={hovered ? '#000000' : color}
            anchorX="center"
            anchorY="middle"
            {...props}
        >
            {title}
        </Text>
    )
}
